# Generated by Django 2.1.1 on 2018-11-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NationReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=8, null=True)),
                ('stu_class', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_account', models.CharField(blank=True, max_length=20, null=True)),
                ('money_count', models.IntegerField(blank=True, null=True)),
                ('money_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('money_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nation_reward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NationSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=16, null=True)),
                ('stu_class', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_account', models.CharField(blank=True, max_length=20, null=True)),
                ('money_count', models.IntegerField(blank=True, null=True)),
                ('money_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('money_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nation_support',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=16, null=True)),
                ('stu_type', models.CharField(blank=True, max_length=8, null=True)),
                ('stu_sex', models.CharField(blank=True, max_length=2, null=True)),
                ('stu_college', models.CharField(blank=True, max_length=32, null=True)),
                ('stu_enrollment', models.IntegerField(blank=True, null=True)),
                ('stu_class', models.CharField(blank=True, max_length=48, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainBasicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=16, null=True)),
                ('stu_type', models.CharField(blank=True, max_length=8, null=True)),
                ('stu_sex', models.CharField(blank=True, max_length=2, null=True)),
                ('stu_college', models.CharField(blank=True, max_length=32, null=True)),
                ('stu_enrollment', models.IntegerField(blank=True, null=True)),
                ('stu_class', models.CharField(blank=True, max_length=48, null=True)),
                ('money_count', models.IntegerField(blank=True, null=True)),
                ('money_year', models.IntegerField(blank=True, null=True)),
                ('money_month', models.CharField(blank=True, max_length=4, null=True)),
                ('money_type', models.CharField(blank=True, max_length=8, null=True)),
                ('money_organization', models.CharField(blank=True, max_length=16, null=True)),
                ('money_name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'main_basic_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NationEncouragement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=16, null=True)),
                ('stu_class', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_account', models.CharField(blank=True, max_length=20, null=True)),
                ('money_count', models.IntegerField(blank=True, null=True)),
                ('money_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('money_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nation_encouragement',
                'managed': True,
            },
        ),
    ]
