# Generated by Django 2.1.1 on 2018-11-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sql', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
